stages:
- name: Build
  steps:
  - runScriptConfig:
      image: nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04
      shellScript: /bin/bash
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example-helloserver:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
